# Generated by Django 6.1.1 on 2026-09-28 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('SIMULATION', 'Test Sandbox / Simulation')], default='RAZORPAY', max_length=20)),
                ('transaction_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('payment_id', models.CharField(blank=True, max_length=120)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending Verification'), ('SUCCESS', 'Success / Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled by User'), ('REFUNDED', 'Refunded')], db_index=True, default='INITIATED', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_description', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_pa_status_c4e513_idx'), models.Index(fields=['booking', 'status'], name='payments_pa_booking_bec69e_idx'), models.Index(fields=['user', 'created_at'], name='payments_pa_user_id_ccae69_idx')],
            },
        ),
    ]
