# Generated by Django 6.1.1 on 2026-09-28 15:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('pincode', models.CharField(max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('facilities', models.CharField(default='Dolby Atmos, 4K Projection, Recliner Seats, Gourmet Food, Parking', help_text='Comma-separated list of amenities', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='theaters/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='theaters.city')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('screen_type', models.CharField(choices=[('STANDARD', 'Standard 2D/3D'), ('IMAX_3D', 'IMAX with Laser 3D'), ('DOLBY_ATMOS', 'Dolby Atmos 4K'), ('4DX', '4DX Motion'), ('GOLD_CLASS', 'Gold Class / Luxury VIP')], default='STANDARD', max_length=20)),
                ('total_seats', models.PositiveIntegerField(default=0)),
                ('rows_count', models.PositiveIntegerField(default=8)),
                ('cols_count', models.PositiveIntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theaters.theater')),
            ],
            options={
                'ordering': ['theater', 'name'],
                'unique_together': {('theater', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_identifier', models.CharField(db_index=True, help_text='e.g. A, B, C', max_length=5)),
                ('seat_number', models.PositiveIntegerField(help_text='e.g. 1, 2, 3')),
                ('seat_code', models.CharField(db_index=True, help_text='e.g. A1, B12', max_length=10)),
                ('seat_type', models.CharField(choices=[('REGULAR', 'Regular'), ('PREMIUM', 'Premium'), ('VIP_RECLINER', 'VIP Recliner')], default='REGULAR', max_length=20)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theaters.screen')),
            ],
            options={
                'ordering': ['row_identifier', 'seat_number'],
                'indexes': [models.Index(fields=['screen', 'seat_code'], name='theaters_se_screen__31da43_idx')],
                'unique_together': {('screen', 'row_identifier', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='ShowSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(db_index=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Standard regular seat price', max_digits=8)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('HOUSEFULL', 'Housefull'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='SCHEDULED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='theaters.screen')),
            ],
            options={
                'ordering': ['show_date', 'start_time'],
                'indexes': [models.Index(fields=['show_date', 'start_time'], name='theaters_sh_show_da_51e050_idx'), models.Index(fields=['movie', 'show_date'], name='theaters_sh_movie_i_c4f5ae_idx')],
            },
        ),
    ]
