# Generated by Django 6.1.1 on 2026-09-28 15:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('role', models.CharField(choices=[('ACTOR', 'Actor / Actress'), ('DIRECTOR', 'Director'), ('PRODUCER', 'Producer'), ('WRITER', 'Writer'), ('MUSIC_DIRECTOR', 'Music Director')], default='ACTOR', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cast/')),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('release_date', models.DateField(db_index=True)),
                ('age_certification', models.CharField(choices=[('U', 'U - Universal (All Ages)'), ('UA 7+', 'UA 7+ (Parental Guidance for Children under 7)'), ('UA 13+', 'UA 13+ (Parental Guidance for Children under 13)'), ('UA 16+', 'UA 16+ (Parental Guidance for Children under 16)'), ('A', 'A - Adults Only (18+)'), ('PG-13', 'PG-13 (Parents Strongly Cautioned)'), ('R', 'R - Restricted')], default='UA 13+', max_length=15)),
                ('youtube_trailer_url', models.URLField(help_text='YouTube video link (e.g., https://www.youtube.com/watch?v=... or https://youtu.be/...)')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='movies/posters/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='movies/banners/')),
                ('status', models.CharField(choices=[('NOW_SHOWING', 'Now Showing'), ('COMING_SOON', 'Coming Soon'), ('ARCHIVED', 'Archived')], db_index=True, default='NOW_SHOWING', max_length=15)),
                ('average_rating', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('is_trending', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
                ('languages', models.ManyToManyField(related_name='movies', to='movies.language')),
            ],
            options={
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cast_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cast_entries', to='movies.castmember')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cast_entries', to='movies.movie')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('movie', 'cast_member')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_members',
            field=models.ManyToManyField(related_name='movies', through='movies.MovieCast', to='movies.castmember'),
        ),
        migrations.CreateModel(
            name='MoviePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movies/gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_posters', to='movies.movie')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], db_index=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('is_verified_viewer', models.BooleanField(default=False, help_text='User booked and watched this movie')),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('is_approved', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam, promotional, or automated content'), ('OFFENSIVE', 'Hate speech, harassment, or abusive language'), ('SPOILERS', 'Contains major unflagged spoilers'), ('INAPPROPRIATE', 'Inappropriate or sexually explicit material'), ('OTHER', 'Other violation')], default='INAPPROPRIATE', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Moderation'), ('REVIEWED', 'Reviewed - Kept'), ('DISMISSED', 'Dismissed'), ('CONTENT_REMOVED', 'Review Removed / Hidden')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='movies.review')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_by', to='movies.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['status', 'release_date'], name='movies_movi_status_66fc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['average_rating', 'is_trending'], name='movies_movi_average_ae5b48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('movie', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewreport',
            unique_together={('review', 'reporter')},
        ),
        migrations.AddIndex(
            model_name='userrecentlyviewed',
            index=models.Index(fields=['user', 'viewed_at'], name='movies_user_user_id_82b03a_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecentlyviewed',
            index=models.Index(fields=['session_key', 'viewed_at'], name='movies_user_session_3d2781_idx'),
        ),
    ]
